spring.application.name=shipmenttrackingportal

server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/logistics_db
spring.datasource.username=postgres
spring.datasource.password=vttamil17

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=2f8f5d61b6cb9e14663114e9fa0d0fb563d2a33cc0f6fe3908c9ef71babb47bc
jwt.expiration.ms=86400000

websocket.allowed-origins=http://localhost:3000