spring.application.name=shipmenttrackingportal

server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/logistics_db
spring.datasource.username=postgres
spring.datasource.password=vttamil17

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# jwt.secret=mysecretkeymysecretkeymysecretkey